remote_theme: pages-themes/minimal
title: Brian Drake
author: Brian Drake
hide_author: true
logo: assets/img/Fire dancing.jpg
description: |
  Hello, I'm Drake
  
  I am currently a PhD student, studying causal AI for decision making. 

  I originally put this website together to document my journey from being an analytical immunoassay scientist, to a machine learning engineer. However, as I have studied and worked more in the field, I developed a love for the dscipline. So I keep studying and working, leading to my website/blog getting bigger!

  Thank you for visiting â˜• 
links:
  - title: Exercism
    url: https://exercism.org/profiles/Drackonack
  - title: Hugging Face
    url: https://huggingface.co/Drackonack
  - title: LinkedIn
    url: https://www.linkedin.com/in/drackonack
paginate: 6
paginate_path: "/posts/:num"
plugins:
  - jekyll-paginate